//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2015-05-19 16:00:46 by 余庆元
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using YF.Core.Data;
namespace T4ConsoleApplication.Entities
{	
    	
	public class Products:EntityBase<int>
    {
								
		/// <summary>
		/// Name 名字
		/// </summary>		
		public string Name { get; set; }
	    				
		/// <summary>
		/// 
		/// </summary>		
		public string Description { get; set; }
	    				
		/// <summary>
		/// 
		/// </summary>		
		public DateTime? LastPurchase { get; set; }
	    										 
    }
}

